import { Theme } from '../../components/types';
import { defaultTheme } from '../../components/types';
const DEFAULT_THEMES: Theme[] = [
  defaultTheme,
  {
    name: 'Sprout',
    cardColor: '#43aa8b',
    fontColor: 'white',
    tabColor: '#0ead69',
    headerColor: '#0ead69',
    bgColor: '#ebf5df',
    iconColor: '#8acb88',
    actionIconColor: '#e4fde1',
    accentColor: '#76c893',
  },
  {
    name: 'Sea Side',
    cardColor: '#5fa8d3',
    fontColor: 'white',
    tabColor: '#0077b6',
    headerColor: '#0077b6',
    bgColor: '#e2eafc',
    iconColor: '#5fa8d3',
    actionIconColor: 'white',
    accentColor: '#82c0cc',
  },
];

export const STORE_THEMES: Theme[] = [
  {
    name: 'Kyoto',
    cardColor: '#e56b6f',
    fontColor: 'white',
    tabColor: '#ff595e',
    headerColor: '#ff595e',
    bgColor: '#ffe5d9',
    iconColor: '#fcb1a6',
    actionIconColor: 'white',
    accentColor: '#f7a399',
  },
  {
    name: 'Cherry Blossoms',
    cardColor: '#FFDFDA',
    fontColor: 'white',
    tabColor: '#FFC1B7',
    headerColor: '#FFC1B7',
    bgColor: '#FFFBFA',
    actionIconColor: '#FFFFFF',
    iconColor: '#FFDFDA',
    accentColor: '#FFEDBF',
  },
  {
    name: 'Hydrangea',
    cardColor: '#EFEEFF',
    fontColor: 'white',
    tabColor: '#E0E0FC',
    headerColor: '#E0E0FC',
    bgColor: '#F8F8FF',
    actionIconColor: '#FFFFFF',
    iconColor: '#EFEEFF',
    accentColor: '#EAD6FF',
  },
  {
    name: 'Sweet Bakery',
    cardColor: '#F2D1B3',
    fontColor: 'white',
    tabColor: '#DABA9C',
    headerColor: '#DABA9C',
    bgColor: '#FFF6EE',
    actionIconColor: '#FFFFFF',
    iconColor: '#F2D1B3',
    accentColor: '#ECD9A9',
  },
  {
    name: 'Tokyo',
    cardColor: '#FF8E8E',
    fontColor: 'white',
    tabColor: '#BEABD6',
    headerColor: '#BEABD6',
    bgColor: '#F8F3FF',
    actionIconColor: '#FFFFFF',
    iconColor: '#D4C6E5',
    accentColor: '#FFFA86',
  },
  {
    name: 'Autumn',
    cardColor: '#FFCA98',
    fontColor: 'white',
    tabColor: '#F5AB66',
    headerColor: '#F5AB66',
    bgColor: '#FFFBED',
    actionIconColor: '#FFFFFF',
    iconColor: '#FFCA98',
    accentColor: '#FFEF99',
  },
  {
    name: 'Shamrock',
    cardColor: '#DAF4DE',
    fontColor: 'white',
    tabColor: '#B9E2C0',
    headerColor: '#B9E2C0',
    bgColor: '#F8F8F8',
    actionIconColor: '#FFFFFF',
    iconColor: '#DAF4DE',
    accentColor: '#DBFFBF',
  },
  {
    name: 'Fruits',
    cardColor: '#FFAEAE',
    fontColor: 'white',
    tabColor: '#FFCBAE',
    headerColor: '#FFCBAE',
    bgColor: '#FFF2F2',
    actionIconColor: '#FFFFFF',
    iconColor: '#FFAEAE',
    accentColor: '#FFF2AE',
  },
  {
    name: 'Magic Girl',
    cardColor: '#E4D7FF',
    fontColor: 'white',
    tabColor: '#FFB4D3',
    headerColor: '#FFB4D3',
    bgColor: '#FFF5F9',
    actionIconColor: '#FFFFFF',
    iconColor: '#E4D7FF',
    accentColor: '#E4D7FF',
  },
  {
    name: 'Home Sweet Home',
    cardColor: '#FFE2C7',
    fontColor: 'white',
    tabColor: '#F98484',
    headerColor: '#F98484',
    bgColor: '#FFFFFF',
    actionIconColor: '#FFFFFF',
    iconColor: '#FFE2C7',
    accentColor: '#FFE1A6',
  },
];
/*

  {
    name: '',
    cardColor: '#',
    fontColor: 'white',
    tabColor: '#',
    headerColor: '#',
    bgColor: '#',
    iconColor: '#',
    actionIconColor: '#',
    accentColor: '#',
  },

  */

export default DEFAULT_THEMES;
