import { Theme } from '../../components/types';
import { defaultTheme } from '../../components/types';
const DEFAULT_THEMES: Theme[] = [
  defaultTheme,
  {
    name: 'Sprout',
    cardColor: '#43aa8b',
    fontColor: '#032F1A',
    tabColor: '#0ead69',
    headerColor: '#0ead69',
    bgColor: '#ebf5df',
    iconColor: '#8acb88',
    actionIconColor: '#e4fde1',
    accentColor: '#76c893',
  },
  {
    name: 'Sea Side',
    cardColor: '#5fa8d3',
    fontColor: '#0A0A47',
    tabColor: '#0077b6',
    headerColor: '#0077b6',
    bgColor: '#e2eafc',
    iconColor: '#5fa8d3',
    actionIconColor: 'white',
    accentColor: '#82c0cc',
  },
];

export const STORE_THEMES: Theme[] = [
  {
    name: 'Kyoto',
    cardColor: '#e56b6f',
    fontColor: '#000000',
    tabColor: '#ff595e',
    headerColor: '#ff595e',
    bgColor: '#ffe5d9',
    iconColor: '#fcb1a6',
    actionIconColor: 'white',
    accentColor: '#f7a399',
  },
  {
    name: 'Cherry Blossoms',
    cardColor: '#FFC1B7',
    fontColor: '#490E0E',
    tabColor: '#FF8B79',
    headerColor: '#FF8B79',
    bgColor: '#FFFBFA',
    actionIconColor: '#FFFFFF',
    iconColor: '#FFA698',
    accentColor: '#FFF1B8',
  },
  {
    name: 'Hydrangea',
    cardColor: '#C0C0F9',
    fontColor: '#262D74',
    tabColor: '#A1A1F6',
    headerColor: '#A1A1F6',
    bgColor: 'white',
    actionIconColor: '#FFFFFF',
    iconColor: '#C0C0F9',
    accentColor: '#EAD6FF',
  },
  {
    name: 'Sweet Bakery',
    cardColor: '#F2C7B3',
    fontColor: '#573611',
    tabColor: '#D3AC87',
    headerColor: '#D3AC87',
    bgColor: 'white',
    actionIconColor: '#FFFFFF',
    iconColor: '#EAD7C6',
    accentColor: '#F2F2B3',
  },
  {
    name: 'Tokyo',
    cardColor: '#FFADF1',
    fontColor: '#6F2D92',
    tabColor: '#42CAFD',
    headerColor: '#42CAFD',
    bgColor: '#FFFCFF',
    actionIconColor: '#FFFFFF',
    iconColor: '#87DEFE',
    accentColor: '#B899FF',
  },
  {
    name: 'Autumn',
    cardColor: '#FFCA98',
    fontColor: '#5A3423',
    tabColor: '#F5AB66',
    headerColor: '#F5AB66',
    bgColor: '#FFFBED',
    actionIconColor: '#FFFFFF',
    iconColor: '#FFCA98',
    accentColor: '#FFEF99',
  },
  {
    name: 'Shamrock',
    cardColor: '#8CCF97',
    fontColor: '#0E3D0A',
    tabColor: '#8CCF97',
    headerColor: '#8CCF97',
    bgColor: 'white',
    actionIconColor: '#FFFFFF',
    iconColor: '#B7E1BE',
    accentColor: '#DBFFBF',
  },
  {
    name: 'Fruits',
    cardColor: '#FFBCAD',
    fontColor: '#761010',
    tabColor: '#FFB68F',
    headerColor: '#FFB68F',
    bgColor: '#FEFFE8',
    actionIconColor: '#FFFFFF',
    iconColor: '#FFD9C5',
    accentColor: '#FFF2AE',
  },
  {
    name: 'Magic Girl',
    cardColor: '#CDB5FF',
    fontColor: '#5C0F49',
    tabColor: '#FF94C0',
    headerColor: '#FF94C0',
    bgColor: '#FFF5F9',
    actionIconColor: '#FFFFFF',
    iconColor: '#FFBAD7',
    accentColor: '#FFB4D3',
  },
  {
    name: 'Berries',
    cardColor: '#83CED4',
    fontColor: '#073742',
    tabColor: '#9984D4',
    headerColor: '#9984D4',
    bgColor: '#FFFFFF',
    actionIconColor: '#FFFFFF',
    iconColor: '#C4B8E6',
    accentColor: '#EEF1BD',
  },
];
/*

  {
    name: '',
    cardColor: '#',
    fontColor: 'white',
    tabColor: '#',
    headerColor: '#',
    bgColor: '#',
    iconColor: '#',
    actionIconColor: '#',
    accentColor: '#',
  },

  */

export default DEFAULT_THEMES;
